version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${PWD}/conf.d:/etc/nginx/conf.d
      - ${PWD}/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
